name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run your tests
      run: tests -sv --alluredir=allure_results
    - name: Upload artifact
      continue-on-error: true
      uses: actions/upload-pages-artifact@v2
      with:
          name: allure_results
          path: allure_results

  generate-report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository branch gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Import artifacts from test run
        uses: actions/download-artifact@v2
        with:
          name: allure-results
          path: allure-results

      - name: Untar the artifact contents
        run: |
          tar -xf allure-results/artifact.tar -C allure-results/
          ls allure-results
          rm allure-results/artifact.tar